const { createClient } = require("@supabase/supabase-js");
const {
  cleanText,
  normalisePriority,
  normaliseSeverity,
  normaliseTimeHorizon,
  findingTypeFromCategory,
  recurrenceKey,
  riskScoreFromRating,
} = require("./reportValidator");

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

async function insertRows(table, rows, options = {}) {
  if (!rows.length) return { data: [], error: null };

  let query = supabase.from(table).insert(rows);
  if (options.select) query = query.select(options.select);

  const result = await query;
  if (result.error) {
    throw new Error(`${table}: ${result.error.message}`);
  }

  return result;
}

async function saveAuditIntelligence({
  auditReportId,
  businessId,
  auditType,
  verifiedReport,
}) {
  const warnings = [];

  const runStep = async (label, work) => {
    try {
      return await work();
    } catch (error) {
      console.error(`${label} persistence failed:`, error);
      warnings.push(`${label}: ${error.message}`);
      return null;
    }
  };

  await runStep("audit_scores", () =>
    insertRows("audit_scores", [
      {
        audit_report_id: auditReportId,
        business_id: businessId || null,
        score_key: "compliance_score",
        score_label: "Compliance Score",
        score_value: verifiedReport.complianceScore,
        score_maximum: 100,
        status:
          verifiedReport.complianceScore >= 80
            ? "strong"
            : verifiedReport.complianceScore >= 60
              ? "attention_required"
              : "high_risk",
        trend_direction: "unknown",
        explanation: `Compliance score generated by the ${auditType} audit module.`,
        metadata: { auditType },
      },
      {
        audit_report_id: auditReportId,
        business_id: businessId || null,
        score_key: "risk_score",
        score_label: "Risk Score",
        score_value: riskScoreFromRating(verifiedReport.overallRiskRating),
        score_maximum: 100,
        status: verifiedReport.overallRiskRating.toLowerCase(),
        trend_direction: "unknown",
        explanation: `Risk index derived from the report rating: ${verifiedReport.overallRiskRating}.`,
        metadata: { auditType, sourceRating: verifiedReport.overallRiskRating },
      },
    ])
  );

  const findingRows = verifiedReport.criticalFindings.map((finding, index) => ({
    audit_report_id: auditReportId,
    business_id: businessId || null,
    finding_type: findingTypeFromCategory(finding.category),
    category: finding.category || "Strategic",
    title: finding.issue.slice(0, 180),
    description: finding.issue,
    severity: normaliseSeverity(finding.severity),
    probability: null,
    business_impact: finding.impact || null,
    evidence: null,
    is_recurring: false,
    recurrence_key: recurrenceKey(finding.category, finding.issue),
    sort_order: index + 1,
    metadata: {
      recommendation: finding.recommendation || null,
      originalPriority: finding.priority || null,
      auditType,
    },
  }));

  await runStep("audit_findings", () => insertRows("audit_findings", findingRows));

  const opportunityRows = verifiedReport.strategicOpportunities.map((item, index) => ({
    audit_report_id: auditReportId,
    business_id: businessId || null,
    category: auditType,
    title: cleanText(item?.opportunity, `Strategic opportunity ${index + 1}`).slice(0, 180),
    description: cleanText(item?.opportunity, "Opportunity details not supplied."),
    potential_impact: cleanText(item?.potentialBenefit) || null,
    estimated_value: null,
    implementation_difficulty: null,
    time_horizon: null,
    priority: "medium",
    rationale: cleanText(item?.recommendedAction) || null,
    sort_order: index + 1,
    metadata: { auditType },
  }));

  await runStep("audit_opportunities", () =>
    insertRows("audit_opportunities", opportunityRows)
  );

  const recommendationRows = verifiedReport.recommendedActions.map((action, index) => ({
    audit_report_id: auditReportId,
    business_id: businessId || null,
    category: auditType,
    title: cleanText(action?.action, `Recommended action ${index + 1}`).slice(0, 180),
    description: cleanText(action?.action, "Action details not supplied."),
    rationale: null,
    expected_outcome: cleanText(action?.expectedOutcome) || null,
    priority: normalisePriority(action?.priority),
    status: "open",
    time_horizon: normaliseTimeHorizon(action?.priority),
    estimated_cost: null,
    estimated_impact: cleanText(action?.expectedOutcome) || null,
    assigned_to: cleanText(action?.owner) || null,
    due_date: null,
    recurrence_key: recurrenceKey(auditType, action?.action),
    sort_order: index + 1,
    metadata: { originalPriority: action?.priority || null, auditType },
  }));

  const recommendationResult = await runStep("audit_recommendations", () =>
    insertRows("audit_recommendations", recommendationRows, { select: "id, sort_order" })
  );

  const recommendationIdsByOrder = new Map(
    (recommendationResult?.data || []).map((row) => [row.sort_order, row.id])
  );

  const actionRows = verifiedReport.recommendedActions.map((action, index) => ({
    audit_report_id: auditReportId,
    business_id: businessId || null,
    recommendation_id: recommendationIdsByOrder.get(index + 1) || null,
    title: cleanText(action?.action, `Priority action ${index + 1}`).slice(0, 180),
    description: cleanText(action?.action) || null,
    priority: normalisePriority(action?.priority),
    status: "not_started",
    assigned_to: cleanText(action?.owner) || null,
    due_date: null,
    success_measure: cleanText(action?.expectedOutcome) || null,
    outcome: null,
    sort_order: index + 1,
  }));

  await runStep("audit_actions", () => insertRows("audit_actions", actionRows));

  return warnings;
}

async function saveAuditReport({
  auditType,
  textToScan,
  verifiedReport,
  businessId,
  accountId,
  modelUsed,
}) {
  const payload = {
    module_id: auditType,
    module_name: auditType,
    status: verifiedReport.status,
    overall_risk_rating: verifiedReport.overallRiskRating,
    compliance_score: verifiedReport.complianceScore,
    executive_summary: verifiedReport.executiveSummary,
    financial_exposure: verifiedReport.financialExposure,
    key_strengths: verifiedReport.keyStrengths,
    critical_findings: verifiedReport.criticalFindings,
    recommended_actions: verifiedReport.recommendedActions,
    strategic_opportunities: verifiedReport.strategicOpportunities,
    missing_information: verifiedReport.missingInformation,
    next_steps: verifiedReport.nextSteps,
    raw_input: textToScan,
    report_json: verifiedReport,
    pdf_generated: false,
  };

  if (businessId) payload.business_id = businessId;
  if (accountId) payload.account_id = accountId;
  if (modelUsed) payload.model_used = modelUsed;

  const { data, error } = await supabase
    .from("audit_reports")
    .insert([payload])
    .select("id")
    .single();

  if (error) throw new Error(error.message);
  return data.id;
}

module.exports = { saveAuditReport, saveAuditIntelligence };
